import test from 'node:test';import assert from 'node:assert/strict';import * as T from 'three';
import {createMemoryScene} from '../src/guild-memory-scene.js';
const entry={position:[1630,114,87],target:[1630,55,3],up:[0,1,0]};
function setup(){const camera=new T.PerspectiveCamera(48,414/896,.2,2400);camera.position.fromArray(entry.position);camera.lookAt(...entry.target);camera.updateMatrixWorld();const source=new T.Mesh(new T.BoxGeometry(3,1,2),new T.MeshStandardMaterial()),memory=createMemoryScene();memory.install(source,'a','b');const group=new T.Group();group.userData.departureAnchors=[];
 for(let i=0;i<20;i++){const x=i<10?(-1.1+i*.09):(.25+(i-10)*.09),position=new T.Vector3(x*90,-30,-90).applyMatrix4(camera.matrixWorld);group.userData.departureAnchors.push({id:'original-'+i,key:'a:b',branch:1,order:x,geometry:source.geometry,material:source.material,worldMatrix:new T.Matrix4().compose(position,camera.quaternion,new T.Vector3(1,1,1))});}memory.captureEntry(group,camera);return {camera,memory,group};}
function points(memory,camera){memory.group.updateMatrixWorld(true);const m=new T.Matrix4();return memory.group.children.filter(x=>x.isInstancedMesh).flatMap(mesh=>Array.from({length:mesh.count},(_,i)=>{mesh.getMatrixAt(i,m);return {id:mesh.userData.anchorIds[i],point:new T.Vector3().setFromMatrixPosition(m).applyMatrix4(mesh.matrixWorld).project(camera)};})).sort((a,b)=>a.point.x-b.point.x);}
// Keeping raw sparse origin angles during departure must reintroduce this hole.
test('original followers close a sparse interior gap early without adding petals',()=>{const {camera,memory}=setup();for(const u of [.35,.55,.8,1,.55]){memory.update({entryPose:entry,entryBlend:u,memoryPhase:0,eventIndex:0},camera,0);const p=points(memory,camera);assert.equal(p.length,20);assert.equal(new Set(p.map(a=>a.id)).size,20);const gaps=p.slice(1).map((a,i)=>a.point.x-p[i].point.x);assert.ok(Math.max(...gaps)/Math.min(...gaps)<1.65,`sparse gap must close by ${u}`);}memory.dispose();});
// Story-local dust at departure projects entirely away from the flight camera.
test('dust covers the rendered flight camera throughout departure',()=>{const {camera,memory}=setup();for(const u of [0,.2,.5,.8,1]){memory.update({entryPose:entry,entryBlend:u,memoryPhase:0,eventIndex:0},camera,0);memory.group.updateMatrixWorld(true);const dust=memory.group.children.find(x=>x.isPoints),p=dust.geometry.attributes.position;let visible=0;for(let i=0;i<p.count;i++){const s=new T.Vector3().fromBufferAttribute(p,i).applyMatrix4(dust.matrixWorld).project(camera);if(Math.abs(s.x)<1&&Math.abs(s.y)<1&&Math.abs(s.z)<1)visible++;}assert.ok(visible>=p.count*.65,`dust coverage lost at ${u}`);assert.ok(p.count>240,'increase mobile dust population');}memory.dispose();});
